model:
    arch: unet
data:
    dataset: pascal
    train_split: train_aug
    val_split: val
    img_rows: 300
    img_cols: 300
    path: /local/riemann1/home/msiam/PASCAL/VOCdevkit/VOC2012/
    sbd_path: /local/riemann1/home/msiam/PASCAL/benchmark_RELEASE/
training:
    train_iters: 300000
    batch_size: 1
    val_interval: 1000
    n_workers: 0
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: fcn8s_pascal_best_model.pkl
